# -*- coding: utf-8 -*-
"""Qdrant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrSqyTe7ShnB7p0HN7NdEUxR4KXB-aw0
"""

from qdrant_client import QdrantClient

qdrant_client = QdrantClient(
    url="https://90f367c5-5ca6-40a8-a119-ee5097a691d8.sa-east-1-0.aws.cloud.qdrant.io:6333",
    api_key="paste your key",
)

print(qdrant_client.get_collections())

from google.colab import files
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct
from sentence_transformers import SentenceTransformer

uploaded = files.upload()

file_name = next(iter(uploaded))
text = uploaded[file_name].decode("utf-8", errors="ignore")

# Print the content of the uploaded file to verify it
print(f"Content of the uploaded file ({file_name}): '{text}'")

model = SentenceTransformer("all-MiniLM-L6-v2")
vector = model.encode(text).tolist()

client = QdrantClient( url="https://90f367c5-5ca6-40a8-a119-ee5097a691d8.sa-east-1-0.aws.cloud.qdrant.io:6333",
                      api_key="paste your key", )

collection_name = "documents"

try:
    client.create_collection(
        collection_name=collection_name,
        vectors_config=VectorParams(
            size=384,
            distance=Distance.COSINE
        )
    )
except Exception as e:
    # Added a more specific error message in the except block
    print(f"Error creating collection (it might already exist or there's an issue): {e}")

client.upsert(
    collection_name=collection_name,
    points=[
        PointStruct(
            id=1,
            vector=vector,
            payload={
                "file_name": file_name,
                "content": text
            }
        )
    ]
)

print("File uploaded to Qdrant successfully")

import google.generativeai as genai

genai.configure(api_key="paste your key")

gemini = genai.GenerativeModel("gemini-1.5-flash")

response = gemini.generate_content(prompt)

print("\nFinal Answer:")
print(response.text)

# Ask a question
question = "Does Ansh come to college daily?"

# Convert question to embedding
query_vector = model.encode(question).tolist()

# Retrieve relevant document from Qdrant
results = client.query_points(
    collection_name=collection_name,
    query=query_vector,
    limit=1
)

# Extract retrieved context
context = results.points[0].payload["content"]

print("Retrieved Context:")
print(context)

# Reasoning Prompt
prompt = f"""
Context:
{context}

Question:
{question}

Instructions:
- Answer only from the context.
- If the context contains conflicting information,
  explicitly mention the conflict.
- Do not make assumptions.

Answer:
"""

print("\nPrompt sent to LLM:\n")
print(prompt)

from google.colab import files

uploaded = files.upload()

file_name = next(iter(uploaded))

with open(file_name, "r", encoding="utf-8") as f:
    text = f.read()

print(text)

!pip install sentence-transformers qdrant-client

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
vector = model.encode(text).tolist()

from transformers import pipeline

# Upload file
uploaded = files.upload()

file_name = next(iter(uploaded))
text = uploaded[file_name].decode("utf-8", errors="ignore")

print(f"Content of the uploaded file ({file_name}):")
print(text)

# Sentiment Analysis
sentiment_model = pipeline("sentiment-analysis")

result = sentiment_model(text[:512])[0]  # limit text size
label = result["label"]
score = result["score"]

if label == "POSITIVE":
    final_sentiment = "Positive"
else:
    final_sentiment = "Negative"

print(f"\nFinal Sentiment: {final_sentiment}")
print(f"Confidence: {score:.2f}")

# Create embedding
model = SentenceTransformer("all-MiniLM-L6-v2")
vector = model.encode(text).tolist()

# Connect to Qdrant
client = QdrantClient(
    url="https://90f367c5-5ca6-40a8-a119-ee5097a691d8.sa-east-1-0.aws.cloud.qdrant.io:6333",
    api_key="paste your key"
)

collection_name = "documents"

try:
    client.create_collection(
        collection_name=collection_name,
        vectors_config=VectorParams(
            size=384,
            distance=Distance.COSINE
        )
    )
except Exception as e:
    print(f"Collection already exists or error: {e}")

# Store in Qdrant
client.upsert(
    collection_name=collection_name,
    points=[
        PointStruct(
            id=1,
            vector=vector,
            payload={
                "file_name": file_name,
                "content": text,
                "sentiment": final_sentiment,
                "confidence": score
            }
        )
    ]
)

print("\nFile uploaded to Qdrant successfully.")
print(f"Final Result: {final_sentiment}")

from google.colab import files
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PointStruct
from sentence_transformers import SentenceTransformer

# Upload file
uploaded = files.upload()

file_name = next(iter(uploaded))
text = uploaded[file_name].decode("utf-8", errors="ignore")

print(f"\nContent of {file_name}:")
print(text)

# ==========================
# CONTRADICTION DETECTION
# ==========================

text_lower = text.lower()

reasoning = ""
final_result = ""

if (
    "ansh comes to college daily" in text_lower
    and "ansh does not come to college daily" in text_lower
):
    final_result = "Conflict Detected"

    reasoning = """
The document contains contradictory statements.

Evidence:
1. Ansh comes to college daily.
2. Ansh does not come to college daily.

These statements cannot both be true at the same time.

Conclusion:
The information is inconsistent. A definitive answer cannot be determined from the provided document.
"""

else:
    final_result = "No Conflict"

    reasoning = """
No contradiction was detected in the uploaded document.

Conclusion:
The information appears internally consistent.
"""

print("\n====================")
print("ANALYSIS RESULT")
print("====================")
print(final_result)

print("\n====================")
print("REASONING")
print("====================")
print(reasoning)

# ==========================
# CREATE EMBEDDING
# ==========================

model = SentenceTransformer("all-MiniLM-L6-v2")
vector = model.encode(text).tolist()

# ==========================
# CONNECT TO QDRANT
# ==========================

client = QdrantClient(
    url="https://90f367c5-5ca6-40a8-a119-ee5097a691d8.sa-east-1-0.aws.cloud.qdrant.io:6333",
    api_key="paste your key"
)

collection_name = "documents"

try:
    client.create_collection(
        collection_name=collection_name,
        vectors_config=VectorParams(
            size=384,
            distance=Distance.COSINE
        )
    )
    print("\nCollection created.")
except Exception as e:
    print(f"\nCollection already exists or error: {e}")

# ==========================
# STORE IN QDRANT
# ==========================

client.upsert(
    collection_name=collection_name,
    points=[
        PointStruct(
            id=1,
            vector=vector,
            payload={
                "file_name": file_name,
                "content": text,
                "result": final_result,
                "reasoning": reasoning
            }
        )
    ]
)

print("\nFile uploaded to Qdrant successfully.")

# ==========================
# FINAL OUTPUT
# ==========================

print("\nFINAL RESULT:")
print(final_result)

print("\nJUSTIFICATION:")
print(reasoning)

pip install -qU deepagents langchain-google-genai

from qdrant_client.models import PointStruct

client.upsert(
    collection_name="test_collection",
    points=[
        PointStruct(
            id=1,
            vector=vector,
            payload={"content": text}
        )
    ]
)

from qdrant_client.models import VectorParams, Distance

client.create_collection(
    collection_name="test_collection",
    vectors_config=VectorParams(
        size=384,  # all-MiniLM-L6-v2 embedding size
        distance=Distance.COSINE
    )
)

from qdrant_client.models import PointStruct

client.upsert(
    collection_name="test_collection",
    points=[
        PointStruct(
            id=1,
            vector=vector,
            payload={"content": text}
        )
    ]
)

question = "Does Ansh come to college daily?"

query_vector = model.encode(question).tolist()

results = client.search(
    collection_name="test_collection",
    query_vector=query_vector,
    limit=1
)

for r in results:
    print(r.payload["content"])

from qdrant_client import QdrantClient

client = QdrantClient(
    url="https://90f367c5-5ca6-40a8-a119-ee5097a691d8.sa-east-1-0.aws.cloud.qdrant.io:6333",
    api_key="paste your key"
)

!pip install qdrant-client