# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQ_tXXsmAiEQvK_9rG1C1YvCbC25d0TE
"""

pip install langchain_openai

pip install langchain_google_genai

import os
from google.colab import userdata
# API Keys
os.environ["GOOGLE_API_KEY"] = userdata.get("geminikey")
os.environ["LANGSMITH_API_KEY"] = userdata.get("task")
# LangSmith settings
os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_PROJECT"] = "my-langchain-project"
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash"
)
response = llm.invoke(
    "Explain how LangSmith tracing works in one sentence."
)
print(response.content)

import os
from google.colab import userdata
from langsmith import Client
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
os.environ["LANGSMITH_API_KEY"] = userdata.get("task")
os.environ["GEMINI_API_KEY"] = userdata.get("geminikey")
client = Client()
model = ChatGoogleGenerativeAI(model="gemini-2.5-flash")
prompt = ChatPromptTemplate.from_template("Tell me a brief {style} joke about {topic}.")
chain = prompt | model
url = client.push_prompt("gemini-joke-generator", object=chain)
print(f"Successfully pushed prompt! Access it here: {url}")